### ISSUE TITLE
CrtScreen Shader appears broken

### ISSUE THREAD

**Issue by MonsterOfCookie** [manuelbua/libgdx-contribs#24]
Hey,

I came across your awesome little library. I am trying to use it with the latest version of libGDX (1.5.3) and I get this error whilst trying the CRT post processor -

java.lang.IllegalArgumentException: no uniform with name 'time' in shader

The example you have on here is, bloom, works just fine.

What can I do to fix this?

**Comment by MonsterOfCookie** [comment]
Looks like the compile optimizes and removes "unused" uniforms.

I am quite new to this, so is this required if the processor is trying to set it? Or as it isn't in the fragment it can be removed?

**Comment by MonsterOfCookie** [comment]
If I change the pedantic  to false it ignores the errors, however I can't seem to get it to work. I either get zero effect, or I get a weird double layering.

I guess with the age of this project, since the last commit, nothing it going to fixed any time soon. Shame

**Comment by manuelbua** [comment]
Hi MonsterOfCookie, thanks for reporting it!
Yeah, at this time i'm quite busy with life, unfortunately, still i've yet to fix some problems of the library and i "paused" my libgdx development for some months now: i would like to fix these and other problems and accept some awesome pull request i had in the last months, but i'm not sure *when* i'll be able to do that.

Sorry if the library doesn't work for you well: it looks odd the CRT post-processor raising that uniform but libgdx could have changed some stuff and this library is probably in need of some work and fixes.

**Comment by MonsterOfCookie** [comment]
Yea, no probs man. I understand.

I wish I understood shaders more so I could help. I was looking at this as a quick fix to potential problem I had.

Thanks anyway

James

**Comment by chrisapril** [comment]
I had the same problem and played around with some configurations. This configurations runs for me:

	int effects = Effect.PhosphorVibrance.v | Effect.Tint.v;
	CrtMonitor crt = new CrtMonitor(width, height,  false, false,
				RgbMode.ChromaticAberrations, effects);
	Combine combine = crt.getCombinePass();

**Comment by MonsterOfCookie** [comment]
Oh cool

What did you do about the time and tint uniform errors?

**Comment by MonsterOfCookie** [comment]
Side note, I just forked and gradlized this. I have the demo up and running and that seems fine. So carrying on from there :)

**Comment by MonsterOfCookie** [comment]
Ok!

Using the demo as an example, I have it all working. Sorry for the confusion on this. 

Look forward to showing you what I do with it :)
