### ISSUE TITLE
`MotionBlur mb = new MotionBlur();` causes android app to close on launch

### ISSUE THREAD

**Issue by bobbyrne01** [manuelbua/libgdx-contribs#30]
Heres a snippet creating a `PostProcessor`. The code below works fine as is, but uncommenting `new MotionBlur()` causes the issue.

Issue only occurs on android though, `MotionBlur` works fine on desktop.

any ideas?

I'm using `gdx 1.6.5` and `libgdx-contribs 1.0.6.1-SNAPSHOT`

dont see any errors in console or logcat

    public class Toolkit extends Game {

        private PostProcessor postProcessor;

        public void create() {
    	
    	    postProcessor = new PostProcessor(false, false, false);
        	ShaderLoader.BasePath = "shaders/";
        	// MotionBlur mb = new MotionBlur(); // TODO uncommenting this line, causes android app to close on launch
            // mb.setBlurOpacity(0.5f);
            // postProcessor.addEffect(mb);
            Bloom bloom = new Bloom( (int)(Gdx.graphics.getWidth() * 0.25f), (int)(Gdx.graphics.getHeight() * 0.25f) );
            bloom.setBloomIntesity(1.5f);
            bloom.enableBlending(GL20.GL_ONE, GL20.GL_ONE_MINUS_SRC_COLOR);
            postProcessor.addEffect(bloom);
        
            this.setScreen(new GameScreen(this));
        }

        public void render() {
            super.render();
        }

        public PostProcessor getPostProcessor() {
            return postProcessor;
        }

        public void setPostProcessor(PostProcessor postProcessor) {
            this.postProcessor = postProcessor;
        }
    }

**Comment by manuelbua** [comment]
Mmm i'm not sure what's happening AND i'm out of the "libgdx" loop now :(
Hopefully @langurmonkey already seen this problem crop up in the past?

**Comment by langurmonkey** [comment]
Sorry for the late reply. I have no knowledge of this issue, but I never tried the motion blur effect on android anyway. A stack trace with the error would come in handy tho.

**Comment by bobbyrne01** [comment]
found this in logs ..

    E/Adreno-SC(15746): <CPPErrorToInfoLog:847>: GLSL line 4: Error: #version number unsupported 
    E/ShaderLoader(15746): OpenGL ES #version <number> is not supported.
    E/ShaderLoader(15746): ERROR: 0:4: '' :     GLSL compile error:  #version number unsupported
    E/ShaderLoader(15746): ERROR: 1 compilation errors.  No code generated.

**Comment by langurmonkey** [comment]
Then try removing the line 3 (`#version 120`) in the file [motionblur.fragment](https://github.com/manuelbua/libgdx-contribs/blob/master/postprocessing/src/main/resources/shaders/motionblur.fragment). This should do the trick.

**Comment by bobbyrne01** [comment]
@langurmonkey that did the trick, i made a pull request with the change #32
