### ISSUE TITLE
Using invalid FrameBuffer Pixmap

### ISSUE THREAD

**Issue by VisualTuber** [manuelbua/libgdx-contribs#39]
The code asks for a FrameBuffer Pixmap, which doesn't exist anymore in newer versions of libgdx.
So it brings up this error:
![unknown](https://user-images.githubusercontent.com/30368284/34454180-95dae212-ed6e-11e7-858d-611d13686c2d.png)
Please fix this or else the library wont work anymore.

**Comment by langurmonkey** [comment]
This was a breaking change added in libgdx ``1.9.7`` and reverted in ``1.9.8``, so it should work with the very latest version (``1.9.8``). See [here](https://libgdx.badlogicgames.com/news.html).
